### ISSUE TITLE
root password won't set

### ISSUE THREAD

**Issue by marshalanson** [advplyr/fotosho#10]
When I type a password in and click, "Submit" the button changes to "Checking" then just sits there. I checked the docker log and I see a message: Set root pash. Eventually an error will appear: Unknown Failure. If I click "Submit" again, it will log in. If I log out and try to login without a password, I get right in.

**Comment by advplyr** [comment]
I'm no longer working on this project so I'm going to archive it. Most of my attention is on https://github.com/advplyr/audiobookshelf now
