### ISSUE TITLE
Gets stuck on large libarys

### ISSUE THREAD

**Issue by ThomasRunting** [advplyr/fotosho#2]
it seems to fail on 
```
168165 Thumbnails Generated: 438:20
Socket Connected 7G58p8oULQUSpZVzAAAF
Config /config /photos /thumbnails
```
just doesnt load

**Comment by advplyr** [comment]
Looks like the scan finished and images generated. Is it still showing the first launch page?

I haven't tested on a collection nearly as large as yours yet. This can be a good stress test, how long did the scan take?
