### ISSUE TITLE
Stuck after scan my library

### ISSUE THREAD

**Issue by logistik777** [advplyr/fotosho#4]
unraid 6.9.2
After the first start and complete a scan a web gui stucks on fetching photos 
and in log:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[1:0x56529943aee0] 1718486 ms: Mark-sweep 1836.6 (2095.8) -> 1836.6 (2095.8) MB, 138.2 / 0.1 ms (average mu = 0.100, current mu = 0.003) allocation failure scavenge might not succeed
[1:0x56529943aee0] 1718625 ms: Mark-sweep 1836.6 (2095.8) -> 1836.6 (2095.8) MB, 139.3 / 0.1 ms (average mu = 0.053, current mu = 0.000) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2065210808d1 <JSObject>
0: builtin exit frame: stringify(this=0x20652109ee79 <Object map = 0x315cb0ec3639>,4,0x35360f5001b9 <null>,0x39a517176b61 <Object map = 0x315cb0efeaf9>,0x20652109ee79 <Object map = 0x315cb0ec3639>)

1: sync [0x22758a62bce9] [/node_modules/simple-json-db/index.js:~145] [pc=0x3623c5756cf6](this=0x39a517176679 <JSONdb map = 0xf96f9178519>)
2: save [0x327ca6c14641] [/server/Database.js:8...

**Comment by advplyr** [comment]
I'm wondering if a single JSON file might be insufficient for large collections. Is your photo directory near or above 100k photos?

Have you tried restarting/rescanning and see if it loads?

**Comment by logistik777** [comment]
Thanksfor answer. I have about 19 000 photos, but also a video clps there.

**Comment by logistik777** [comment]
One more always when I start a container after stop it before, web ui starts again from the beginning scanning all my phohtos. It`s  OK?

**Comment by advplyr** [comment]
Yes that is normal, the scan is to check that the database is in sync with the directory since it was last seen. I'm going to try to do that second scan in the background.

**Comment by logistik777** [comment]
> Yes that is normal, the scan is to check that the database is in sync with the directory since it was last seen. I'm going to try to do that second scan in the background.

Will be great, because it takes for me about 30 min

**Comment by advplyr** [comment]
The database is updated and scans are now run in the background. If you still have the Docker image, you can `force update` to grab those updates.
Fotosho doesn't support videos yet, but I'm welcoming any and all pull requests.
