### ISSUE TITLE
Shuffle Slideshow option

### ISSUE THREAD

**Issue by Michael-Bell** [advplyr/fotosho#5]
Is adding a "shuffle slideshow" option a feature that might be considered implementing? 

Would it be better to put a "Shuffle/Randomized" sort option in the dropdown, or have a second Check box for "shuffle" when the slideshow is running?

**Comment by advplyr** [comment]
That is a good idea. I was going to add an input to change the time between slides today, so I'll try to add this in too.

**Comment by advplyr** [comment]
This has been added to the slideshow. I moved the slideshow options to the top right. Thanks for the suggestion.
