### ISSUE TITLE
Subfolders are not taking into account

### ISSUE THREAD

**Issue by adamotte** [advplyr/fotosho#8]
I have a Photos folders structure as this : 
- _Photos_
   - Archived
      - Archived Album
   - **Album X**
   - **Year 1**
      - Year 1 Album 1
      - Year 1 Album 2
   - Year 2

Currently, fotosho only scan first level of folder so in the previous exemple i will see only photos (if there are) of **bold** folder in the exemple before.

**Comment by advplyr** [comment]
The scanner is setup to recursively scan, are you sure you are pointing to the Photos directory?
